DELETE FROM login WHERE password = crypt('passer123', password);

INSERT INTO login (passtype, password) 
VALUES ('login', crypt('passer123', gen_salt('bf')) ),
('alter', crypt('passer123', gen_salt('bf'))),
('delete', crypt('passer123', gen_salt('bf')));

INSERT INTO categories_modeles(id, nom_categorie)
VALUES(0, 'Autres');

INSERT INTO categories_modeles(nom_categorie)
VALUES ('Tenues'), ('Accessoire'), ('matieres_premieres');

INSERT INTO facturation(mois, count) VALUES(1, 0);
